site_name: VerdictDB Documentation
site_url: 'https://docs.verdictdb.org/'

copyright: 'Copyright &copy; 2018 The University of Michigan'

# Pages
nav:
  - Home: index.md
  - Getting Started:
    - Quickstart: getting_started/quickstart.md
    - Download / Install: getting_started/install.md
    - Connecting to Data Sources: getting_started/connection.md
    - Creating Scrambles: getting_started/scrambling.md
    - Simple Querying: getting_started/querying.md
    - Stream Querying: getting_started/streaming.md
    # - Result Structure: getting_started/results.md
  - How it works:
    - Basics: how_it_works/basics.md
    - Architecture: how_it_works/architecture.md
    - Query Processing: how_it_works/query_processing.md
  - Tutorial:
    - Setup Databases (optional):
      - MySQL: tutorial/setup/mysql.md
      - Apache Spark: tutorial/setup/spark.md
    - Load TPC-H Data: tutorial/tpch.md
    - Example VerdictDB App:
      - MySQL: tutorial/examples/mysql.md
      - Apache Spark: tutorial/examples/spark.md
    - ML-based Analytics: tutorial/advanced.md
  - Reference:
    - Query Syntax:
      - Scrambling: reference/scrambling_syntax.md
      - Select Query: reference/query_syntax.md
    - Javadoc: reference/javadoc.md
  #   - VerdictDB Queries: reference/supported_queries.md

# Appearance
theme:
  name: 'material'
  font:
    text: Open Sans
    code: Inconsolata
  palette:
    primary: 'Deep Purple'
    accent: 'Deep Purple'
  feature:
    tabs: true
  logo: 'images/verdictdb-logo-icon.png'
  favicon: 'images/verdictdb-favicon.png'
repo_name: 'mozafari/verdictdb'
repo_url: 'https://github.com/mozafari/verdictdb'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'javascripts/extra.js'


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
